# Generated by Django 4.1.13 on 2025-03-30 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', djongo.models.fields.JSONField()),
                ('address', models.TextField()),
                ('amenities', djongo.models.fields.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('images', djongo.models.fields.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classrooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='classrooms.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rental_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalrequest',
            index=models.Index(fields=['classroom'], name='rental_requ_classro_20c04f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalrequest',
            index=models.Index(fields=['teacher'], name='rental_requ_teacher_13dc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalrequest',
            index=models.Index(fields=['status'], name='rental_requ_status_f36a10_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['school'], name='classrooms_school__8fee6e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_available'], name='classrooms_is_avai_c1ece5_idx'),
        ),
    ]
