# Generated by Django 4.1.13 on 2025-04-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalRequest',
        ),
    ]
