# Generated by Django 4.1.13 on 2025-04-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('registration', 'Registration Badge'), ('points_100', '100 Points Badge'), ('points_500', '500 Points Badge'), ('points_1000', '1000 Points Badge'), ('gold', 'Gold Medal (1st place)'), ('silver', 'Silver Medal (2nd place)'), ('bronze', 'Bronze Medal (3rd place)'), ('top_10', 'Top 10 Badge')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_url', models.URLField()),
                ('points_required', models.IntegerField(default=0)),
            ],
        ),
    ]
