# Generated by Django 3.1.12 on 2025-04-02 19:28

import bson.objectid
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school', 'School')], db_index=True, max_length=10)),
                ('points', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rank', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('badges', djongo.models.fields.JSONField(default=list)),
                ('profile_sync_version', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['role', 'rank'],
            },
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['points_required'], 'verbose_name_plural': 'Badges'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='badge_type',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='id',
        ),
        migrations.AddField(
            model_name='badge',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='rank_required',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='badge',
            name='role_specific',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('school', 'School')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='points_required',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='badge',
            table='badges',
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['role', 'rank'], name='leaderboard_role_b276be_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['role', '-points'], name='leaderboard_role_2f926d_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['user_id', 'role'], name='user_role_idx'),
        ),
    ]
