# Generated by Django 3.1.12 on 2025-04-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20250402_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='user_email',
        ),
    ]
