# Generated by Django 4.2.20 on 2025-03-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='study_year',
        ),
    ]
