# Generated by Django 4.2.20 on 2025-03-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_student_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='teacher',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
