# Generated by Django 3.1.12 on 2025-04-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_materials_link',
            field=models.URLField(blank=True, help_text='Google Drive link for course materials', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Google Meet link for online sessions', max_length=512, null=True),
        ),
    ]
