# Generated by Django 3.1.12 on 2025-04-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_price_per_hour_and_more'),
        ('courses', '0002_auto_20250403_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.AddField(
            model_name='course',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_materials_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['contract'], name='courses_contrac_4ce745_idx'),
        ),
    ]
