# Generated by Django 3.1.12 on 2025-04-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatroom',
            table='chat_chatroom',
        ),
    ]
