# Generated by Django 3.1.12 on 2025-04-04 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_alter_contract_price_per_hour_and_more'),
        ('courses', '0003_auto_20250403_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_transferred', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(choices=[('student_teacher', 'Student to Teacher'), ('teacher_school', 'Teacher to School')], max_length=20)),
                ('payment_method', models.CharField(default='EDAHABIA', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('chargily_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fee_transferred_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transferred', models.BooleanField(default=False)),
                ('transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='payments.payment')),
            ],
            options={
                'verbose_name_plural': 'Platform Fees',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sender'], name='payments_pa_sender__7382f6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient'], name='payments_pa_recipie_ab6a09_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_type'], name='payments_pa_transac_d1d8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['platform_fee_transferred'], name='payments_pa_platfor_cb0cf3_idx'),
        ),
    ]
