# Generated by Django 4.1.13 on 2025-03-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price_per_hour',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
