# Generated by Django 4.1.13 on 2025-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
